[package]
name = "counter"
version = "0.1.0"
authors = ["Padunk <abraham.agel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stdweb = "0.4.20"
yew = "0.11.0"